// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateProductInput struct {
	Name      string  `json:"name"`
	Price     float64 `json:"price"`
	Stock     int32   `json:"stock"`
	CreatedAt string  `json:"createdAt"`
}

type DeleteProductResponse struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateProductInput struct {
	Name  *string  `json:"name,omitempty"`
	Price *float64 `json:"price,omitempty"`
}
